export const TEXT_CONFIG = {
    'profile' : 'Profile',
    'name' : 'Mohan Chidambaram',
    'jobTitle' : 'Full Stack Developer',
    'tabItemSkills' : 'Skills',
    'tabItemWorkHistory' : 'Work History',
    'tabItemAcademics' : 'Academics',
    'tabItemCert' : 'Courses and Certifications',
    'tabItemOthers' : 'Others',
    'sideMenuHome' : 'Home',
    'sideMenuPersonal' : 'Personal Information',
    'sideMenuEmployment' : 'Current Employment Information',
    'sideMenuContact' : 'Contact Me',
    'currentOrganization' : 'IVTL Infoview Technologies Pvt. Ltd.',
    'previousOrganization' : 'Annam Software Pvt. Ltd.',
    'expandAllButton' :  'Expand All',
    'collapseAllButton' :  'Collapse All',
    'courses' : 'Courses',
    'certifications' : 'Certifications',
    'courseBE':'BE',
    'courseHsc':'HSC',
    'courseSslc':'SSLC',
    'collegeName':'Institute of Road and Transport Technology (IRTT)',
    'schoolName':'Amala Matriculation Higher Secondary School',
    'locationGobi' : 'Gobichettipalayam',
    'locationErode' : 'Erode',
    'locationChennai' : 'Chennai',
    'percentageSymbol' : ' %',
    'courseLabel' : 'Course',
    'instituteLabel' : 'Institution',
    'periodLabel' : 'Period',
    'scoreLabel' : 'Score',
    'bestThingLabel' : 'Best Thing',
    'colonSymbol' : ' : ',
    'achieveHeader' : 'Achievements',
    'activityHeader' : 'Additional Activties',
    'relExpLabel' : 'Relevant Experience',
    'hasCertLabel' : 'Has Certification',
    'levelLabel' : 'Level',
    'categoryLabrl' : 'Category',
    'levelBeginner' : 'Beginner',
    'levelGood' : 'Good',
    'levelExpert' : 'Expert',
    'years' : 'Years',
    'months' : 'Months',
    'skillSet' : 'Skill Set',
    'downloadHint' : 'Download the Profile'
}

export const CONTENT_CONFIG = {
    'quoteContent' : "Don't stop when you're tired, Stop when you're Done !",
    'summaryContent1' : 'Senior Full Stack Web Developer offering more than',
    'summaryContent2' : ' of expertise and outstanding performance in Java and Angular, who developed full-stack web applications which processed, analyzed, and rendered data visually. Recognized team player and outstanding performer awaiting to apply the skills in full potential  to produce a software product that meets all goals and objectives outlined by the customer. ',

    'perfMgmtProject' : 'SCM – COST (Performance Management)',
    'perfMgmtPeriod' : 'OCT 2018 – Current',
    'rolePerfMgmt1' : 'Analysed the catalogue requirement document given by the client and created Design Document.',
    'rolePerfMgmt2' : 'Designed the User Interface (UI) using XML and LESS for end user.',
    'rolePerfMgmt3' : 'Developed the screen using Java and Java script on HUE framework (Internal framework developed using Spring MVC).',
    'rolePerfMgmt4' : 'Business calculations using the data fetched from RDB by MySQL .',
    'rolePerfMgmt5' : 'Reviewed code for standards using SonarQube, debugged problems and corrected issues.',
    'rolePerfMgmt6' : 'Deployed the code in server by using Jenkins .',
    'rolePerfMgmt7' : 'Performed Unit Testing on the screens for Quality Assurance.',
    'mfgProject' : 'SCM – Manufacturing Cost',
    'mfgPeriod' : 'JUN 2018 – OCT 2018',
    'roleMfg1' : 'Discussed requirements on existing screens with customers and directly addressed concerns.',
    'roleMfg2' : 'Created screen layout and user interface using HTML and CSS practices .',
    'roleMfg3' : 'Developed robust Java and Angular code for web screens.',
    'roleMfg4' : 'Delivered performance-driven and user-centric screens that met all business requirements.',
    'roleMfg5' : 'Established milestones for projects and prepared all team members to meet aggressive deadlines .',
    'annamProject' : 'Trainee Software Developer',
    'annamPeriod' : 'DEC 2017 – JUN 2018',
    'roleAnnam1' : 'Understood the Working flow of Software development .',
    'roleAnnam2' : 'Provided solutions for critical problems and developed modules in Java .',
    'roleAnnam3' : 'Built, tested and deployed scalable, highly available and modular software products . ',

    'certJava' : 'Oracle Certified Associate Java SE7 Programmer',
    'certC' : 'Advanced Diploma in C Programming (ADCP) from CSC Computer Education',
    'courseJava' : 'Completed Core Java Course at NIIT ',
    'courseC' : 'Completed Programming in C and C++ Course at CSC Computer Education',
    'coursePython' : 'Pursuing Python Course at World Quant University',
    'courseML' : 'Pursuing Machine Learning Course at World Quant University',

    'courseBEFull':'Bachelor of Engineering - Electronics and Communication Engineering (ECE)',
    'courseHscFull':'Higher Secondary Course',
    'courseSslcFull':'SSLC Course',
    'collegeBest' : 'Elected as the Student Secretary in the final year (2018).',
    'schoolBest' : ' Topper of the School.',
    'sslcPeriod' : '2011 - 2012',
    'hscPeriod' : '2012 - 2014',
    'collegePeriod' : '2014 - 2018',

    'achieve1' : 'Rewarded as Best Team Player for the year 2019 at IVTL.',
    'achieve2' : 'Recognized as Top 5 Performer of the 2018 batch at IVTL.',
    'achieve3' : 'Winner - General Quiz at IRTT.',
    'achieve4' : 'Winner - Marketing at IRTT.',
    'achieve5' : 'Runner up in English Just a Minute (JAM) at IRTT',
    'achieve6' : 'Runner up in Project Expo at IRTT.',
    'achieve7' : 'Runner up in Circuit Debugging at IRTT.',
    'activity1' : 'Posed as a Lab lead for 3 members at IVTL.',
    'activity2' : 'Organized Inauguration Event for fresher at IRTT.',
    'activity3' : 'Posed as Secretary in final year Symposium at IRTT.',
}

export const SKILL_INFO = {
    'skillSet' : 'Skill Set',
    'categoryFront' : 'Front End',
    'categoryBack' : 'Back End',
    'categoryDb' : 'Data Base',
    'categoryTool' : 'Tools',
    'categoryFlow' : 'Work Flow',
    'categoryGeneral' : 'General',
    'categoryServer' : 'Server',
    'java' : 'Java 8',
    'python' : 'Python 3',
    'spring' : 'Spring Framework',
    'springMvc' : 'Spring MVC Framework',
    'springBoot' : 'Spring Boot Framework',
    'rdb' : 'Relational Database Management System (RDBMS)',
    'cassandra' : 'Cassandra DB',
    'sql' : 'MySQL',
    'angular' : 'Angular 8',
    'js' : 'Java Script',
    'html' : 'HTML',
    'css' : 'CSS',
    'less' : 'LESS',
    'git' : 'Git Lab',
    'tomcat' : 'Tomcat',
    'jenkins' : 'Jenkins',
    'sonar' : 'Sonar Qube',
    'agile' : 'Agile Methodology',
    'sdlc' : 'Software Development Life Cycle (SDLC)',
    'analysis' : 'Technical Analysis',
    'web' : 'Web User Interface',
    'cr' : 'Code Review',
    'unitTest' : 'Unit Testing',
    'c' : 'C and C++',
    'teamMgmt' : 'Team Management',
    'problemSolving' : 'Problem Resolution'
}

export const PERSONAL_INFO = {
    'nameLabel' : 'Full Name',
    'genderLabel' : 'Gender',
    'fatherLabel' : 'Father',
    'motherLabel' : 'Mother',
    'dobLabel' : 'Date of Birth',
    'addressLabel' : 'Address',
    'villageLabel' : 'Village',
    'cityLabel' : 'City',
    'districtLabel' : 'District',
    'stateLabel' : 'State',
    'postalLabel' : 'Postal Code',
    'nationalityLabel' : 'Nationality',
    'languageLabel' : 'Language Known',
    'hobbyLabel' : 'Hobbies',
    'gender' : 'Male',
    'fatherName' : 'Chidambaram K',
    'motherName' : 'Vijayalakshmi C',
    'dob' : '30 Dec 1996',
    'address' : '42/37, Periya Kattu Thottam',
    'village' : 'Ayalur',
    'city' : 'Gobichettipalayam',
    'district' : 'Erode',
    'state' : 'Tamil Nadu',
    'nation' : 'Indian',
    'pin' : '638453',
    'language' : 'Tamil , English',
    'hobby' : 'Swimming, Playing Chess, Listening to some good vibes'
}

export const EMPLOYMENT_INFO = {
    'organizationLabel' : 'Organization',
    'designationLabel' : 'Designation',
    'designation' : 'Senior Full Stack Developer',
    'clientLabel' : 'Client',
    'client' : 'Works Applications(WAP), Japan',
    'currentLocationLabel' : 'Current Location',
    'preferedLocationLabel' : 'Preferred Location',
    'preferedLocation' : 'PAN India',
    'cctcLabel' : 'Current CTC',
    'ectcLabel' : 'Expected CTC',
    'cctc' : '7 Lakhs (Indian Rupees)',
    'ectc' : '10 Lakhs (Indian Rupees)',
    'npLabel' : 'Notice Period',
    'np' : '30 Days',
    'openLabel' : 'Is Open to Work',
    'isOpen' : 'Yes',
}

export const CONTACT_INFO = {
    'mobileLabel' : 'Mobile No.',
    'alternateLabel' : 'Alternate Mobile',
    'mob1' : '(+91) 99941-28922',
    'mob2' : '(+91) 74021-32225',
    'mailLabel' : 'Mail',
    'mail' : 'mohan.ayalur@gmail.com',
    'linkedInLabel' : 'LinkedIn'
}